# Generated by Django 5.2.9 on 2025-12-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Entregable",
        ),
        migrations.DeleteModel(
            name="Estudiante",
        ),
        migrations.DeleteModel(
            name="Profesor",
        ),
    ]
